import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from "next/router";
import styles from '/styles/Summoner.module.css'

import SummonerProfile from 'containers/summoner/SummonerProfile';
import Rank from 'containers/summoner/Rank';
import RecentChampion from 'containers/summoner/RecentChampion';
import MostChampion from 'containers/summoner/MostChampion';
import MatchesTop from 'containers/summoner/MatchesTop';
import Matches from 'containers/summoner/Matches';

const Home: NextPage = () => {
  const router = useRouter();
  console.log(router);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <SummonerProfile />
        <div className={styles.hr} />
        <div className={styles.layout}>
          <div className={styles.layout_sub}>
            <Rank rank={1} />
            <Rank rank={null} />
            <RecentChampion />
            <MostChampion />
          </div>
          <div className={styles.layout_sub}>
            <MatchesTop />
            <Matches />
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Home
